### ISSUE TITLE
M1 Elasticsearch 실행 오류 문의

### ISSUE THREAD

**Issue by xexi** [bareun-nlp/bareun-es-plugin#2]
안녕하세요? M1 에서 config.properties 설정 후 빌드한 플러그인을 활용해(정상 동작 확인) repo 와 동일한 Dockerfile 로 
Elasticsearch(8.5.2) 실행시 발생하는 오류 문의 드립니다. (바른 서버도 정상 구동 중입니다.)

**System**
java 19.0.2 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)

Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)
Maven home: /opt/homebrew/Cellar/maven/3.9.2/libexec
Java version: 20.0.1, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/20.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: ko_KR, platform encoding: UTF-8
OS name: "mac os x", version: "13.4.1", arch: "aarch64", family: "mac"

**Error**

```json
{
   "@timestamp":"2023-06-22T07:23:50.996Z",
   "log.level":"ERROR",
   "message":"fatal exception while booting Elasticsearch",
   "ecs.version":"1.2.0",
   "service.name":"ES_ECS",
   "event.dataset":"elasticsearch.server",
   "process.thread.name":"main",
   "log.logger":"org.elasticsearch.bootstrap.Elasticsearch",
   "elasticsearch.node.name":"elasticsearch",
   "elasticsearch.cluster.name":"docker-cluster",
   "error.type":"org.elasticsearch.ElasticsearchException",
   "error.message":"Could not find plugin class [org.elasticsearch.plugin.analysis.baikal.NlpPlugin]",
   "error.stack_trace":"org.elasticsearch.ElasticsearchException: Could not find plugin class [org.elasticsearch.plugin.analysis.baikal.NlpPlugin]\n\tat org.elasticsearch.server@8.5.2/org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:575)\n\tat org.elasticsearch.server@8.5.2/org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:470)\n\tat org.elasticsearch.server@8.5.2/org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:290)\n\tat org.elasticsearch.server@8.5.2/org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:159)\n\tat org.elasticsearch.server@8.5.2/org.elasticsearch.plugins.PluginsService.lambda$getPluginsServiceCtor$14(PluginsService.java:634)\n\tat org.elasticsearch.server@8.5.2/org.elasticsearch.node.Node.<init>(Node.java:411)\n\tat org.elasticsearch.server@8.5.2/org.elasticsearch.node.Node.<init>(Node.java:318)\n\tat org.elasticsearch.server@8.5.2/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:214)\n\tat org.elasticsearch.server@8.5.2/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:214)\n\tat org.elasticsearch.server@8.5.2/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)\nCaused by: java.lang.ClassNotFoundException: org.elasticsearch.plugin.analysis.baikal.NlpPlugin\n\tat java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)\n\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)\n\tat java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)\n\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)\n\tat java.base/java.lang.Class.forName0(Native Method)\n\tat java.base/java.lang.Class.forName(Class.java:495)\n\tat java.base/java.lang.Class.forName(Class.java:474)\n\tat org.elasticsearch.server@8.5.2/org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:573)\n\t... 9 more\n"
}
```

**Comment by gih2yun** [comment]
```
org.elasticsearch.ElasticsearchException:
Could not find plugin class [org.elasticsearch.plugin.analysis.baikal.NlpPlugin]
  at org.elasticsearch.server@8.5.2/org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:575)
  at org.elasticsearch.server@8.5.2/org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:470)
  at org.elasticsearch.server@8.5.2/org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:290)
  at org.elasticsearch.server@8.5.2/org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:159)
  at org.elasticsearch.server@8.5.2/org.elasticsearch.plugins.PluginsService.lambda$getPluginsServiceCtor$14(PluginsService.java:634)
  at org.elasticsearch.server@8.5.2/org.elasticsearch.node.Node.<init>(Node.java:411)
  at org.elasticsearch.server@8.5.2/org.elasticsearch.node.Node.<init>(Node.java:318)
  at org.elasticsearch.server@8.5.2/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:214)
  at org.elasticsearch.server@8.5.2/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:214)
  at org.elasticsearch.server@8.5.2/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.plugin.analysis.baikal.NlpPlugin
  at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
  at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
  at java.base/java.lang.Class.forName0(Native Method)
  at java.base/java.lang.Class.forName(Class.java:495)
  at java.base/java.lang.Class.forName(Class.java:474)
  at org.elasticsearch.server@8.5.2/org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:573)
  ..
```

**Comment by gih2yun** [comment]
위 에러는 별다른 게 아니고, 전형적인 클래스 로더 오류입니다.

만들어진 zip 파일을 플러그인 디렉토리에 제대로 설치를 했는지 확인해주시면 좋겠습니다.
